// <auto-generated />
using System;
using DiceApi.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiceApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190515100017_AddedRollValuesMigration")]
    partial class AddedRollValuesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiceApi.Entities.Roll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("RoomId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Rolls");
                });

            modelBuilder.Entity("DiceApi.Entities.RollValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxValue");

                    b.Property<int?>("RollId");

                    b.Property<int>("UserRoomId");

                    b.Property<int?>("UserRoomRoomId");

                    b.Property<int?>("UserRoomUserId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("RollId");

                    b.HasIndex("UserRoomUserId", "UserRoomRoomId");

                    b.ToTable("RollValue");
                });

            modelBuilder.Entity("DiceApi.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DiceApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiceApi.Entities.UserRoom", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoomId");

                    b.Property<bool>("Owner");

                    b.HasKey("UserId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("UserRooms");
                });

            modelBuilder.Entity("DiceApi.Entities.Roll", b =>
                {
                    b.HasOne("DiceApi.Entities.Room", "Room")
                        .WithMany("Rolls")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiceApi.Entities.User", "User")
                        .WithMany("Rolls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiceApi.Entities.RollValue", b =>
                {
                    b.HasOne("DiceApi.Entities.Roll")
                        .WithMany("RollValues")
                        .HasForeignKey("RollId");

                    b.HasOne("DiceApi.Entities.UserRoom", "UserRoom")
                        .WithMany()
                        .HasForeignKey("UserRoomUserId", "UserRoomRoomId");
                });

            modelBuilder.Entity("DiceApi.Entities.UserRoom", b =>
                {
                    b.HasOne("DiceApi.Entities.Room", "Room")
                        .WithMany("RoomUsers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiceApi.Entities.User", "User")
                        .WithMany("UserRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
